/*
 *  dat2c -- host build tool for the MFC-DOS ScottFree port.
 *
 *  Reads a Scott Adams TRS-80 format .dat and emits a C file of initialized
 *  tables (Header/Items/Rooms/Verbs/Nouns/Messages/Actions) for scott.c to
 *  link against. This moves all database parsing to build time, so the 6502
 *  binary carries no parser, no fscanf, and no heap.
 *
 *  The parser below is ScottFree 1.14's LoadDatabase/ReadString (Alan Cox,
 *  GPL), adapted to populate local arrays and then print them as C.
 *
 *  Build/run on the host:  cc -o dat2c dat2c.c
 *                          ./dat2c adv01.dat > adv01_data.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "scott.h"

static Header H;
static Item   *Items_;
static Room   *Rooms_;
static char  **Verbs_;
static char  **Nouns_;
static char  **Messages_;
static Action *Actions_;
static int     Ver, Adv;

static void Fatal(const char *m) { fprintf(stderr, "dat2c: %s\n", m); exit(1); }
static void *Alloc(int n) { void *p = malloc(n); if (!p) Fatal("out of memory"); return p; }

/* ScottFree ReadString: a quoted string, with backtick (0x60) -> '"'. */
static char *ReadString(FILE *f)
{
    char tmp[1024];
    int c, nc, ct = 0;
    do { c = fgetc(f); } while (c != EOF && isspace(c));
    if (c != '"') Fatal("initial quote expected");
    for (;;) {
        c = fgetc(f);
        if (c == EOF) Fatal("EOF in string");
        if (c == '"') { nc = fgetc(f); if (nc != '"') { ungetc(nc, f); break; } }
        if (c == 0x60) c = '"';
        tmp[ct++] = c;
    }
    tmp[ct] = 0;
    { char *t = Alloc(ct + 1); memcpy(t, tmp, ct + 1); return t; }
}

static void LoadDatabase(FILE *f)
{
    int ni, na, nw, nr, mc, pr, tr, wl, lt, mn, trm, ct;
    short lo;
    Action *ap; Room *rp; Item *ip;

    ct = 0;
    if (fscanf(f, "%*d %d %d %d %d %d %d %d %d %d %d %d",
               &ni, &na, &nw, &nr, &mc, &pr, &tr, &wl, &lt, &mn, &trm) < 10)
        Fatal("invalid database (bad header)");
    H.NumItems = ni;    Items_   = Alloc(sizeof(Item)   * (ni + 1));
    H.NumActions = na;  Actions_ = Alloc(sizeof(Action) * (na + 1));
    H.NumWords = nw;    H.WordLength = wl;
    Verbs_ = Alloc(sizeof(char *) * (nw + 1));
    Nouns_ = Alloc(sizeof(char *) * (nw + 1));
    H.NumRooms = nr;    Rooms_ = Alloc(sizeof(Room) * (nr + 1));
    H.MaxCarry = mc;    H.PlayerRoom = pr;  H.Treasures = tr;
    H.LightTime = lt;   H.NumMessages = mn;
    Messages_ = Alloc(sizeof(char *) * (mn + 1));
    H.TreasureRoom = trm;

    ct = 0; ap = Actions_;
    while (ct < na + 1) {
        if (fscanf(f, "%hd %hd %hd %hd %hd %hd %hd %hd",
                   &ap->Vocab, &ap->Condition[0], &ap->Condition[1],
                   &ap->Condition[2], &ap->Condition[3], &ap->Condition[4],
                   &ap->Action[0], &ap->Action[1]) != 8)
            Fatal("bad action line");
        ap++; ct++;
    }
    for (ct = 0; ct < nw + 1; ct++) { Verbs_[ct] = ReadString(f); Nouns_[ct] = ReadString(f); }
    rp = Rooms_;
    for (ct = 0; ct < nr + 1; ct++) {
        fscanf(f, "%hd %hd %hd %hd %hd %hd", &rp->Exits[0], &rp->Exits[1],
               &rp->Exits[2], &rp->Exits[3], &rp->Exits[4], &rp->Exits[5]);
        rp->Text = ReadString(f); rp++;
    }
    for (ct = 0; ct < mn + 1; ct++) Messages_[ct] = ReadString(f);
    ip = Items_;
    for (ct = 0; ct < ni + 1; ct++) {
        ip->Text = ReadString(f);
        ip->AutoGet = strchr(ip->Text, '/');
        if (ip->AutoGet && strcmp(ip->AutoGet, "//") && strcmp(ip->AutoGet, "/*")) {
            char *t;
            *ip->AutoGet++ = 0;
            t = strchr(ip->AutoGet, '/');
            if (t != NULL) *t = 0;
        }
        fscanf(f, "%hd", &lo);
        ip->Location = (unsigned char)lo;
        ip->InitialLoc = ip->Location;
        ip++;
    }
    /* Skip the per-action comment strings. */
    for (ct = 0; ct < na + 1; ct++) free(ReadString(f));
    fscanf(f, "%d", &Ver);
    fscanf(f, "%d", &Adv);
}

/* Print a C string literal for s (may contain newlines / quotes). */
static void EmitStr(const char *s)
{
    if (s == NULL) { fputs("0", stdout); return; }
    putchar('"');
    for (; *s; s++) {
        unsigned char c = (unsigned char)*s;
        switch (c) {
            case '"':  fputs("\\\"", stdout); break;
            case '\\': fputs("\\\\", stdout); break;
            case '\n': fputs("\\n",  stdout); break;
            case '\r': fputs("\\r",  stdout); break;
            case '\t': fputs("\\t",  stdout); break;
            default:
                if (c >= 0x20 && c < 0x7f) putchar(c);
                else printf("\\%03o", c);   /* 3-digit octal: unambiguous */
        }
    }
    putchar('"');
}

static void Emit(const char *src)
{
    int i, j;
    printf("/* Auto-generated by dat2c from %s -- do not edit. */\n", src);
    printf("#include \"scott.h\"\n\n");

    printf("Header GameHeader = {%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d};\n\n",
           0, H.NumItems, H.NumActions, H.NumWords, H.NumRooms, H.MaxCarry,
           H.PlayerRoom, H.Treasures, H.WordLength, H.LightTime,
           H.NumMessages, H.TreasureRoom);

    printf("char *Verbs[] = {\n");
    for (i = 0; i <= H.NumWords; i++) { putchar(' '); EmitStr(Verbs_[i]); fputs(",\n", stdout); }
    printf("};\n\n");

    printf("char *Nouns[] = {\n");
    for (i = 0; i <= H.NumWords; i++) { putchar(' '); EmitStr(Nouns_[i]); fputs(",\n", stdout); }
    printf("};\n\n");

    printf("char *Messages[] = {\n");
    for (i = 0; i <= H.NumMessages; i++) { putchar(' '); EmitStr(Messages_[i]); fputs(",\n", stdout); }
    printf("};\n\n");

    printf("Room Rooms[] = {\n");
    for (i = 0; i <= H.NumRooms; i++) {
        fputs(" {", stdout); EmitStr(Rooms_[i].Text); fputs(",{", stdout);
        for (j = 0; j < 6; j++) printf("%d%s", Rooms_[i].Exits[j], j < 5 ? "," : "");
        fputs("}},\n", stdout);
    }
    printf("};\n\n");

    printf("Item Items[] = {\n");
    for (i = 0; i <= H.NumItems; i++) {
        fputs(" {", stdout); EmitStr(Items_[i].Text);
        printf(",%d,%d,", Items_[i].Location, Items_[i].InitialLoc);
        EmitStr(Items_[i].AutoGet); fputs("},\n", stdout);
    }
    printf("};\n\n");

    printf("Action Actions[] = {\n");
    for (i = 0; i <= H.NumActions; i++) {
        printf(" {%u,{%u,%u,%u,%u,%u},{%u,%u}},\n",
               Actions_[i].Vocab, Actions_[i].Condition[0], Actions_[i].Condition[1],
               Actions_[i].Condition[2], Actions_[i].Condition[3], Actions_[i].Condition[4],
               Actions_[i].Action[0], Actions_[i].Action[1]);
    }
    printf("};\n\n");

    printf("int GameVersion = %d;\n", Ver);
    printf("int GameAdventure = %d;\n", Adv);
}

int main(int argc, char *argv[])
{
    FILE *f;
    if (argc != 2) { fprintf(stderr, "usage: %s game.dat > game_data.c\n", argv[0]); return 1; }
    f = fopen(argv[1], "r");
    if (!f) { perror(argv[1]); return 1; }
    LoadDatabase(f);
    fclose(f);
    Emit(argv[1]);
    return 0;
}
